# Generated by Django 6.0.3 on 2026-06-27 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Table',
            field=models.CharField(choices=[('pvt', 'Privet'), ('pub', 'Public'), ('win', 'Window')], null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
