# Generated by Django 6.0.3 on 2026-06-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_table_alter_booking_guest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Table',
            field=models.CharField(choices=[], max_length=1, null=True),
        ),
    ]
