# Generated by Django 6.0.3 on 2026-06-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='Table',
            field=models.CharField(choices=[('pvt', 'Privet'), ('pub', 'Public'), ('win', 'Window')], max_length=3, null=True),
        ),
    ]
