# Generated by Django 6.0.3 on 2026-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_tabletype_alter_booking_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Table',
        ),
        migrations.AddField(
            model_name='booking',
            name='Table_Type',
            field=models.CharField(choices=[('pvt', 'Privet'), ('pub', 'Public'), ('win', 'Window')], default='pvt', max_length=3, null=True),
        ),
    ]
